### ISSUE TITLE
End to End SerDe for Transaction Data

### ISSUE THREAD

**Issue by mattgeddes** [versatus/lasr#122]
In order to satify #119 and child tasks, we need to pass our data blobs into the archive crate as a structures that can be serialised and deserialised by serde. The archive crate will serialise this into a BSON document for MongoDB (or something else in future), and write the data, and will do the same in reverse on reads.

This task is to take the _transaction data_ structures that we need to archive, and to ensure that we can call serde over these and with no issues. Once we identify the relevant data structure(s), we can add `Serialize, Deserialize` to each module and structure, and probably write a quick unit test to show that we go from struct->JSON/BSON/whatever->struct through serde and be done with it.

This is related to #121 , but is for transaction data vs account data.

**Comment by andrewvious** [comment]
Through testing with TiKV persistence store, end to end serde for Transaction data has been done.
