### ISSUE TITLE
Call Archive write path from da_client crate

### ISSUE THREAD

**Issue by mattgeddes** [versatus/lasr#123]
Once we have the create path for the archive create, this task is to add calls to it from the `da_client` crate within LASR. Once this path exists, we can probably even run with these changes on one of the test networks. That'll not only give us data to help testing the read path, but also gives other applications a chance to start looking at the data and experimenting with it (a future block explorer, for example).

We should add more detail here once we know more about where we're going to hook into this in the LASR code.

**Comment by eureka-cpu** [comment]
@andrewvious can this be closed? Would you mind going through the issues listed and weeding out what still needs to be done?

**Comment by andrewvious** [comment]
Closed by #155 using TiKV persistence store.
