### ISSUE TITLE
Set up write path for `Transaction`s to Persistence Store

### ISSUE THREAD

**Issue by andrewvious** [versatus/lasr#190]
Add logic to store validated txn's with TiKV

**Comment by eureka-cpu** [comment]
Edit: Write transaction data into an external TiKV instance, outside of the protocol. Long term this should be handled by archival node.

**Comment by eureka-cpu** [comment]
DaClient should handle passing the account's tree's state and root hashes with the relevant transactions to the DA

**Comment by eureka-cpu** [comment]
Devnet: Just store the whole tree
Mainnet: Store only necessary data to reassemble the tree when needed, then update the tree data on the Account

**Comment by andrewvious** [comment]
Ref #192 
Closing due to redundancy
