### ISSUE TITLE
Impl `MerkleTree` on `Account`s

### ISSUE THREAD

**Issue by andrewvious** [versatus/lasr#192]
Using jmt's Jellyfish Merkle Tree: `https://github.com/penumbra-zone/jmt` establish a space for `Transaction`s to be stored in the `Account` structure, to later be stored in our Persistence Store as a whole.

**Comment by andrewvious** [comment]
Ref #190  
extra context from meeting**

**Comment by eureka-cpu** [comment]
Closing since we've decided not to implement this feature.
