### ISSUE TITLE
Account data failing to be pushed to persistence 

### ISSUE THREAD

**Issue by andrewvious** [versatus/lasr#232]
Currently our TiKV persistence store is not accepting updates to accounts, or insertion of new accounts. This error is unexpected, as other area's in our protocol that use TiKV and are working fine (blocks_processed). The issue started around 8:40am today, and the error handling needs to be updated for if this occurs again. 

It is worth noting that TiKV broadcasts warnings of their product API being `not suitable for production use` or `not yet stable`

**Comment by eureka-cpu** [comment]
This was due to system resources being unavailable, right? Can this be closed?

**Comment by andrewvious** [comment]
The issue was solved by freeing up system resources, and a helpful error message was added Ref #233
